id = "typst"
name = "Typst"
description = "Typst support."
version = "0.0.1"
schema_version = 1
authors = ["WeetHet <stas.ale66@gmail.com>"]
repository = "https://codeberg.org/weethet/typst.zed"

[language_servers.tinymist]
name = "Typst language support"
language = "Typst"

[grammars.typst]
repository = "https://github.com/uben0/tree-sitter-typst"
commit = "1ad9724e4e4ea5ab81192e843e74cf664eacc59b"
